# Generated by Django 6.1.1 on 2026-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontact',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
