# Generated by Django 6.1.1 on 2026-09-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_companycontact_is_verified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companycontact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='normalized_name',
            field=models.CharField(db_index=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='companycontact',
            unique_together={('task', 'normalized_name')},
        ),
    ]
