# Generated by Django 6.1.1 on 2026-09-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_alter_companycontact_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontact',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
