# Generated by Django 6.1.1 on 2026-09-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_companycontact_is_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_persons', to='research.companycontact')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
    ]
