# Generated by Django 6.1.1 on 2026-09-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_keyperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtask',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
