# Generated by Django 6.1.1 on 2026-10-01 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_researchtask_duration_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('requested_count', models.PositiveIntegerField()),
                ('scheduled_send_date', models.DateField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DRAFTING', 'Drafting'), ('SCHEDULED', 'Scheduled'), ('SENDING', 'Sending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PAUSED', 'Paused')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='companycontact',
            name='email_draft_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='email_draft_subject',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='is_mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='mail_draft_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='mail_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='mail_sent_to',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='research.emailcampaign'),
        ),
    ]
